version: '3.1'

services:
  odoo:
    image: odoo:17.0
    container_name: odoo
    restart: unless-stopped
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASSWORD:-odoo}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/logs:/var/log/odoo
    command: --workers=2 --logfile=/var/log/odoo/odoo.log

  db:
    image: postgres:15
    container_name: odoo-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:-odoo}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
