{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ include "task-management.name" . }}-database
    {{- include "task-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "task-management.name" . }}-database
{{- end }}
